using System;
using System.Collections.Generic;
using Microsoft.Xna.Framework;

namespace TileQuest
{
    public enum TileType
    {
        Grass,     // base walkable ground
        TallGrass, // walkable; triggers wild encounters
        Tree,      // impassable obstacle
        Rock,      // impassable obstacle
        Wall       // sentinel only — the default for out-of-bounds coordinates;
                   // never actually placed on the generated map
    }

    // DSA note: tiles are stored in a Dictionary<Point, TileType> (hash table) rather
    // than a bounds-checked 2D array, so lookups by grid coordinate are O(1). This is
    // the "Inventory & tile lookups -> Hash Table" piece from the project plan.
    public class TileMap
    {
        public int Width { get; }
        public int Height { get; }
        public int TileSize { get; }
        public Point SpawnPoint { get; }
        public bool IsFullyConnected { get; }

        private readonly Dictionary<Point, TileType> _tiles;

        public TileMap(int width, int height, int tileSize)
        {
            Width = width;
            Height = height;
            TileSize = tileSize;

            // The map is now an open forest generated by ForestGenerator
            // (recursive cluster scattering of trees/rocks/tall grass) instead
            // of the earlier BSP dungeon. GetTile/IsWalkable/AllTiles are
            // still the only surface Player and Game1 talk to, so nothing
            // outside this class needed to change for the swap.
            _tiles = ForestGenerator.Generate(width, height, new Random(), out var spawnPoint);
            SpawnPoint = spawnPoint;

            // Verify every walkable tile is reachable from spawn via a graph +
            // BFS over the generated tiles. ForestGenerator already repairs
            // any isolated pockets internally, so this should always report
            // fully connected — it's a second, independent verification layer
            // at map-initialization time.
            var graph = new TileGraph(_tiles);
            IsFullyConnected = graph.IsFullyConnected(SpawnPoint, out var unreachableCount);
            Console.WriteLine(IsFullyConnected
                ? "[TileGraph] BFS connectivity check: OK, all ground reachable from spawn."
                : $"[TileGraph] BFS connectivity check: WARNING — {unreachableCount} tile(s) unreachable from spawn.");
        }

        public TileType GetTile(Point gridPos)
        {
            return _tiles.TryGetValue(gridPos, out var tile) ? tile : TileType.Wall;
        }

        // Tree and rock anchors are checked against their collision bounds
        // below, so their visible size controls the space they occupy.
        public bool IsWalkable(Point gridPos)
        {
            var tile = GetTile(gridPos);
            if (tile != TileType.Grass && tile != TileType.TallGrass &&
                tile != TileType.Tree && tile != TileType.Rock)
            {
                return false;
            }

            var playerBounds = new Rectangle(
                gridPos.X * TileSize + TileSize / 4,
                gridPos.Y * TileSize + TileSize * 2 / 3,
                TileSize / 2,
                TileSize / 4);

            for (int x = gridPos.X - 1; x <= gridPos.X + 1; x++)
            {
                for (int y = gridPos.Y - 1; y <= gridPos.Y + 1; y++)
                {
                    var obstaclePosition = new Point(x, y);
                    var obstacleTile = GetTile(obstaclePosition);
                    if (obstacleTile == TileType.Tree &&
                        playerBounds.Intersects(DrawTree.GetCollisionBounds(obstaclePosition, TileSize)))
                    {
                        return false;
                    }
                    if (obstacleTile == TileType.Rock &&
                        playerBounds.Intersects(DrawRock.GetBounds(obstaclePosition, TileSize)))
                    {
                        return false;
                    }
                }
            }

            return true;
        }

        public IEnumerable<KeyValuePair<Point, TileType>> AllTiles() => _tiles;
    }
}
