using System;
using System.Collections.Generic;
using Microsoft.Xna.Framework;

namespace TileQuest
{
    public enum TileType
    {
        Grass,     // base walkable ground
        TallGrass, // walkable; triggers wild encounters
        Tree,      // impassable obstacle
        Rock,      // impassable obstacle
        Wall       // sentinel only — the default for out-of-bounds coordinates;
                   // never actually placed on the generated map
    }

    // DSA note: tiles are stored in a Dictionary<Point, TileType> (hash table) rather
    // than a bounds-checked 2D array, so lookups by grid coordinate are O(1). This is
    // the "Inventory & tile lookups -> Hash Table" piece from the project plan.
    public class TileMap
    {
        public int Width { get; }
        public int Height { get; }
        public int TileSize { get; }
        public Point SpawnPoint { get; }
        public bool IsFullyConnected { get; }

        private readonly Dictionary<Point, TileType> _tiles;

        public TileMap(int width, int height, int tileSize)
        {
            Width = width;
            Height = height;
            TileSize = tileSize;

            // The map is now an open forest generated by ForestGenerator
            // (recursive cluster scattering of trees/rocks/tall grass) instead
            // of the earlier BSP dungeon. GetTile/IsWalkable/AllTiles are
            // still the only surface Player and Game1 talk to, so nothing
            // outside this class needed to change for the swap.
            _tiles = ForestGenerator.Generate(width, height, new Random(), out var spawnPoint);
            SpawnPoint = spawnPoint;

            // Verify every walkable tile is reachable from spawn via a graph +
            // BFS over the generated tiles. ForestGenerator already repairs
            // any isolated pockets internally, so this should always report
            // fully connected — it's a second, independent verification layer
            // at map-initialization time.
            var graph = new TileGraph(_tiles);
            IsFullyConnected = graph.IsFullyConnected(SpawnPoint, out var unreachableCount);
            Console.WriteLine(IsFullyConnected
                ? "[TileGraph] BFS connectivity check: OK, all ground reachable from spawn."
                : $"[TileGraph] BFS connectivity check: WARNING — {unreachableCount} tile(s) unreachable from spawn.");
        }

        public TileType GetTile(Point gridPos)
        {
            return _tiles.TryGetValue(gridPos, out var tile) ? tile : TileType.Wall;
        }

        // Explicit allow-list rather than "not Wall": now that there are
        // multiple non-walkable entity types (Tree, Rock), only tile types
        // that are deliberately meant to be walked on count as walkable.
        public bool IsWalkable(Point gridPos)
        {
            var tile = GetTile(gridPos);
            return tile == TileType.Grass || tile == TileType.TallGrass;
        }

        public IEnumerable<KeyValuePair<Point, TileType>> AllTiles() => _tiles;
    }
}
